################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../USB_Host_Shield_2_0/BTD.cpp \
../USB_Host_Shield_2_0/BTHID.cpp \
../USB_Host_Shield_2_0/MiniDSP.cpp \
../USB_Host_Shield_2_0/PS3BT.cpp \
../USB_Host_Shield_2_0/PS3USB.cpp \
../USB_Host_Shield_2_0/PS4Parser.cpp \
../USB_Host_Shield_2_0/PS5Parser.cpp \
../USB_Host_Shield_2_0/PS5Trigger.cpp \
../USB_Host_Shield_2_0/PSBuzz.cpp \
../USB_Host_Shield_2_0/SPP.cpp \
../USB_Host_Shield_2_0/UHS2_gpio.cpp \
../USB_Host_Shield_2_0/Usb.cpp \
../USB_Host_Shield_2_0/Wii.cpp \
../USB_Host_Shield_2_0/XBOXOLD.cpp \
../USB_Host_Shield_2_0/XBOXONE.cpp \
../USB_Host_Shield_2_0/XBOXONESParser.cpp \
../USB_Host_Shield_2_0/XBOXRECV.cpp \
../USB_Host_Shield_2_0/XBOXUSB.cpp \
../USB_Host_Shield_2_0/adk.cpp \
../USB_Host_Shield_2_0/cdc_XR21B1411.cpp \
../USB_Host_Shield_2_0/cdcacm.cpp \
../USB_Host_Shield_2_0/cdcftdi.cpp \
../USB_Host_Shield_2_0/cdcprolific.cpp \
../USB_Host_Shield_2_0/hidboot.cpp \
../USB_Host_Shield_2_0/hidcomposite.cpp \
../USB_Host_Shield_2_0/hidescriptorparser.cpp \
../USB_Host_Shield_2_0/hiduniversal.cpp \
../USB_Host_Shield_2_0/hidusagetitlearrays.cpp \
../USB_Host_Shield_2_0/masstorage.cpp \
../USB_Host_Shield_2_0/max_LCD.cpp \
../USB_Host_Shield_2_0/message.cpp \
../USB_Host_Shield_2_0/parsetools.cpp \
../USB_Host_Shield_2_0/usbh_midi.cpp \
../USB_Host_Shield_2_0/usbhid.cpp \
../USB_Host_Shield_2_0/usbhub.cpp 

OBJS += \
./USB_Host_Shield_2_0/BTD.o \
./USB_Host_Shield_2_0/BTHID.o \
./USB_Host_Shield_2_0/MiniDSP.o \
./USB_Host_Shield_2_0/PS3BT.o \
./USB_Host_Shield_2_0/PS3USB.o \
./USB_Host_Shield_2_0/PS4Parser.o \
./USB_Host_Shield_2_0/PS5Parser.o \
./USB_Host_Shield_2_0/PS5Trigger.o \
./USB_Host_Shield_2_0/PSBuzz.o \
./USB_Host_Shield_2_0/SPP.o \
./USB_Host_Shield_2_0/UHS2_gpio.o \
./USB_Host_Shield_2_0/Usb.o \
./USB_Host_Shield_2_0/Wii.o \
./USB_Host_Shield_2_0/XBOXOLD.o \
./USB_Host_Shield_2_0/XBOXONE.o \
./USB_Host_Shield_2_0/XBOXONESParser.o \
./USB_Host_Shield_2_0/XBOXRECV.o \
./USB_Host_Shield_2_0/XBOXUSB.o \
./USB_Host_Shield_2_0/adk.o \
./USB_Host_Shield_2_0/cdc_XR21B1411.o \
./USB_Host_Shield_2_0/cdcacm.o \
./USB_Host_Shield_2_0/cdcftdi.o \
./USB_Host_Shield_2_0/cdcprolific.o \
./USB_Host_Shield_2_0/hidboot.o \
./USB_Host_Shield_2_0/hidcomposite.o \
./USB_Host_Shield_2_0/hidescriptorparser.o \
./USB_Host_Shield_2_0/hiduniversal.o \
./USB_Host_Shield_2_0/hidusagetitlearrays.o \
./USB_Host_Shield_2_0/masstorage.o \
./USB_Host_Shield_2_0/max_LCD.o \
./USB_Host_Shield_2_0/message.o \
./USB_Host_Shield_2_0/parsetools.o \
./USB_Host_Shield_2_0/usbh_midi.o \
./USB_Host_Shield_2_0/usbhid.o \
./USB_Host_Shield_2_0/usbhub.o 

CPP_DEPS += \
./USB_Host_Shield_2_0/BTD.d \
./USB_Host_Shield_2_0/BTHID.d \
./USB_Host_Shield_2_0/MiniDSP.d \
./USB_Host_Shield_2_0/PS3BT.d \
./USB_Host_Shield_2_0/PS3USB.d \
./USB_Host_Shield_2_0/PS4Parser.d \
./USB_Host_Shield_2_0/PS5Parser.d \
./USB_Host_Shield_2_0/PS5Trigger.d \
./USB_Host_Shield_2_0/PSBuzz.d \
./USB_Host_Shield_2_0/SPP.d \
./USB_Host_Shield_2_0/UHS2_gpio.d \
./USB_Host_Shield_2_0/Usb.d \
./USB_Host_Shield_2_0/Wii.d \
./USB_Host_Shield_2_0/XBOXOLD.d \
./USB_Host_Shield_2_0/XBOXONE.d \
./USB_Host_Shield_2_0/XBOXONESParser.d \
./USB_Host_Shield_2_0/XBOXRECV.d \
./USB_Host_Shield_2_0/XBOXUSB.d \
./USB_Host_Shield_2_0/adk.d \
./USB_Host_Shield_2_0/cdc_XR21B1411.d \
./USB_Host_Shield_2_0/cdcacm.d \
./USB_Host_Shield_2_0/cdcftdi.d \
./USB_Host_Shield_2_0/cdcprolific.d \
./USB_Host_Shield_2_0/hidboot.d \
./USB_Host_Shield_2_0/hidcomposite.d \
./USB_Host_Shield_2_0/hidescriptorparser.d \
./USB_Host_Shield_2_0/hiduniversal.d \
./USB_Host_Shield_2_0/hidusagetitlearrays.d \
./USB_Host_Shield_2_0/masstorage.d \
./USB_Host_Shield_2_0/max_LCD.d \
./USB_Host_Shield_2_0/message.d \
./USB_Host_Shield_2_0/parsetools.d \
./USB_Host_Shield_2_0/usbh_midi.d \
./USB_Host_Shield_2_0/usbhid.d \
./USB_Host_Shield_2_0/usbhub.d 


# Each subdirectory must supply rules for building sources it contributes
USB_Host_Shield_2_0/BTD.o: ../USB_Host_Shield_2_0/BTD.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/BTD.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/BTHID.o: ../USB_Host_Shield_2_0/BTHID.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/BTHID.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/MiniDSP.o: ../USB_Host_Shield_2_0/MiniDSP.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/MiniDSP.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/PS3BT.o: ../USB_Host_Shield_2_0/PS3BT.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/PS3BT.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/PS3USB.o: ../USB_Host_Shield_2_0/PS3USB.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/PS3USB.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/PS4Parser.o: ../USB_Host_Shield_2_0/PS4Parser.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/PS4Parser.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/PS5Parser.o: ../USB_Host_Shield_2_0/PS5Parser.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/PS5Parser.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/PS5Trigger.o: ../USB_Host_Shield_2_0/PS5Trigger.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/PS5Trigger.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/PSBuzz.o: ../USB_Host_Shield_2_0/PSBuzz.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/PSBuzz.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/SPP.o: ../USB_Host_Shield_2_0/SPP.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/SPP.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/UHS2_gpio.o: ../USB_Host_Shield_2_0/UHS2_gpio.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/UHS2_gpio.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/Usb.o: ../USB_Host_Shield_2_0/Usb.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/Usb.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/Wii.o: ../USB_Host_Shield_2_0/Wii.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/Wii.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/XBOXOLD.o: ../USB_Host_Shield_2_0/XBOXOLD.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/XBOXOLD.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/XBOXONE.o: ../USB_Host_Shield_2_0/XBOXONE.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/XBOXONE.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/XBOXONESParser.o: ../USB_Host_Shield_2_0/XBOXONESParser.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/XBOXONESParser.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/XBOXRECV.o: ../USB_Host_Shield_2_0/XBOXRECV.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/XBOXRECV.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/XBOXUSB.o: ../USB_Host_Shield_2_0/XBOXUSB.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/XBOXUSB.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/adk.o: ../USB_Host_Shield_2_0/adk.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/adk.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/cdc_XR21B1411.o: ../USB_Host_Shield_2_0/cdc_XR21B1411.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/cdc_XR21B1411.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/cdcacm.o: ../USB_Host_Shield_2_0/cdcacm.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/cdcacm.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/cdcftdi.o: ../USB_Host_Shield_2_0/cdcftdi.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/cdcftdi.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/cdcprolific.o: ../USB_Host_Shield_2_0/cdcprolific.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/cdcprolific.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/hidboot.o: ../USB_Host_Shield_2_0/hidboot.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/hidboot.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/hidcomposite.o: ../USB_Host_Shield_2_0/hidcomposite.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/hidcomposite.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/hidescriptorparser.o: ../USB_Host_Shield_2_0/hidescriptorparser.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/hidescriptorparser.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/hiduniversal.o: ../USB_Host_Shield_2_0/hiduniversal.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/hiduniversal.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/hidusagetitlearrays.o: ../USB_Host_Shield_2_0/hidusagetitlearrays.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/hidusagetitlearrays.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/masstorage.o: ../USB_Host_Shield_2_0/masstorage.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/masstorage.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/max_LCD.o: ../USB_Host_Shield_2_0/max_LCD.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/max_LCD.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/message.o: ../USB_Host_Shield_2_0/message.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/message.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/parsetools.o: ../USB_Host_Shield_2_0/parsetools.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/parsetools.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/usbh_midi.o: ../USB_Host_Shield_2_0/usbh_midi.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/usbh_midi.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/usbhid.o: ../USB_Host_Shield_2_0/usbhid.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/usbhid.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
USB_Host_Shield_2_0/usbhub.o: ../USB_Host_Shield_2_0/usbhub.cpp USB_Host_Shield_2_0/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER '-DARDUINO=100' -DSTM32F4 '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DSTM32F446xx -DDEBUG -c -I../Core/Inc -I../Drivers/SSD1306 -I../USB_Host_Shield_2_0 -I../Arduino_libs -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O1 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"USB_Host_Shield_2_0/usbhub.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

