(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var c="Translate",e=this||self;function f(a,m){a=a.split(".");var b=e;a[0]in b||"undefined"==typeof b.execScript||b.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===m?b[d]&&b[d]!==Object.prototype[d]?b=b[d]:b=b[d]={}:b[d]=m}var g=/^[\w+/_-]+[=]{0,2}$/,h=null;function k(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&g.test(a)?a:""}function l(a){return a};var n={0:c,1:"Cancel",2:"Close",3:function(a){return"Google has automatically translated this page to: "+a},4:function(a){return"Translated to: "+a},5:"Error: The server could not complete your request. Try again later.",6:"Learn more",7:function(a){return"Powered by "+a},8:c,9:"Translation in progress",10:function(a){return"Translate this page to: "+(a+" using Google Translate?")},11:function(a){return"View this page in: "+a},12:"Show original",13:"The content of this local file will be sent to Google for translation using a secure connection.",
14:"The content of this secure page will be sent to Google for translation using a secure connection.",15:"The content of this intranet page will be sent to Google for translation using a secure connection.",16:"Select Language",17:function(a){return"Turn off "+(a+" translation")},18:function(a){return"Turn off for: "+a},19:"Always hide",20:"Original text:",21:"Contribute a better translation",22:"Contribute",23:"Translate all",24:"Restore all",25:"Cancel all",26:"Translate sections to my language",
27:function(a){return"Translate everything to "+a},28:"Show original languages",29:"Options",30:"Turn off translation for this site",31:null,32:"Show alternative translations",33:"Click on words above to get alternative translations",34:"Use",35:"Drag with shift key to reorder",36:"Click for alternative translations",37:"Hold down the shift key, click, and drag the words above to reorder.",38:"Thank you for contributing your translation suggestion to Google Translate.",39:"Manage translation for this site",
40:"Click a word for alternative translations, or double-click to edit directly",41:"Original text",42:c,43:c,44:"Your correction has been submitted.",45:"Error: The language of the webpage is not supported.",46:"Language Translate Widget"};var p;function q(a,m){this.g=m===r?a:""}q.prototype.toString=function(){return this.g+""};var r={};var t=window.google&&google.translate&&google.translate._const;
if(t){var u;a:{for(var v=[],w=[""],x=0;x<w.length;++x){var y=w[x].split(","),z=y[0];if(z){var A=Number(y[1]);if(!(!A||.1<A||0>A)){var B=Number(y[2]),C=new Date,D=1E4*C.getFullYear()+100*(C.getMonth()+1)+C.getDate();!B||B<D||v.push({version:z,ratio:A,h:B})}}}var E=0,F=window.location.href.match(/google\.translate\.element\.random=([\d\.]+)/),G=Number(F&&F[1])||Math.random();for(x=0;x<v.length;++x){var H=v[x];E+=H.ratio;if(1<=E)break;if(G<E){u=H.version;break a}}u="TE_20210224_00"}var I="/element/%s/e/js/element/element_main.js".replace("%s",
u);if("0"==u){var J=" element %s e js element element_main.js".split(" ");J[J.length-1]="main.js";I=J.join("/").replace("%s",u)}if(t._cjlc)t._cjlc(t._pas+t._pah+I);else{var K=t._pas+t._pah+I,L,M="SCRIPT",N=document;M=String(M);"application/xhtml+xml"===N.contentType&&(M=M.toLowerCase());L=N.createElement(M);L.type="text/javascript";L.charset="UTF-8";var O,P;if(void 0===p){var Q=null,R=e.trustedTypes;if(R&&R.createPolicy){try{Q=R.createPolicy("goog#html",{createHTML:l,createScript:l,createScriptURL:l})}catch(a){e.console&&
e.console.error(a.message)}p=Q}else p=Q}var S=(P=p)?P.createScriptURL(K):K;O=new q(S,r);L.src=O instanceof q&&O.constructor===q?O.g:"type_error:TrustedResourceUrl";var T;var U=L.ownerDocument&&L.ownerDocument.defaultView;U&&U!=e?T=k(U.document):(null===h&&(h=k(e.document)),T=h);T&&L.setAttribute("nonce",T);var V=document.getElementsByTagName("head")[0];V||(V=document.body.parentNode.appendChild(document.createElement("head")));V.appendChild(L)}f("google.translate.m",n);f("google.translate.v",u)};}).call(window)
